/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia5;

import javax.swing.JOptionPane;

/**
 *
 * @author marcello
 */
public class GUIA4 extends javax.swing.JFrame {

    /**
     * Creates new form GUIA4
     */
    public GUIA4() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPantalla = new javax.swing.JTextField();
        txtBateria = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtFlash = new javax.swing.JTextField();
        txtCamara = new javax.swing.JTextField();
        txtGpu = new javax.swing.JTextField();
        txtGarantia = new javax.swing.JTextField();
        txtCpu = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPrincipal = new javax.swing.JTextField();
        txtSecundaria = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtRam = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        cbbmarca = new javax.swing.JComboBox();

        jTextField4.setText("jTextField4");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Xperia", 1, 11)); // NOI18N
        jLabel1.setText("GUIA 4: CALIFICACION OFERTA SMARTPHONE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 16, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 439, 10));

        jLabel2.setText("Tamaño de pantalla:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 58, -1, -1));

        jLabel3.setText("Capacidad de bateria en ma:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 89, -1, -1));

        jLabel4.setText("Referencia en marca:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 127, -1, -1));

        jLabel5.setText("Precio:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 165, -1, -1));

        jLabel6.setText("Pixelaje de la camara:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 314, -1, -1));

        jLabel7.setText("Tiempo de Garantia:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 352, -1, -1));

        jLabel8.setText("CPU:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 390, -1, -1));

        jLabel9.setText("GPU:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 434, -1, -1));

        jLabel10.setText("RAM:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 469, -1, -1));

        txtPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPantallaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 55, 175, -1));
        getContentPane().add(txtBateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 86, 175, -1));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 162, 175, -1));
        getContentPane().add(txtFlash, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 276, 175, -1));
        getContentPane().add(txtCamara, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 314, 175, -1));
        getContentPane().add(txtGpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 428, 175, -1));
        getContentPane().add(txtGarantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 352, 175, -1));
        getContentPane().add(txtCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 175, -1));

        jButton2.setFont(new java.awt.Font("Hall Fetica Wide", 0, 11)); // NOI18N
        jButton2.setText("Calcular Puntaje");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 504, -1, -1));

        jLabel11.setText("Camara principal:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 203, -1, -1));

        jLabel12.setText("Camara secundaria:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 238, -1, -1));
        getContentPane().add(txtPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 175, -1));
        getContentPane().add(txtSecundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 238, 175, -1));

        jLabel13.setText("Flash:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 276, -1, -1));
        getContentPane().add(txtRam, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 466, 175, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jButton1.setFont(new java.awt.Font("Hall Fetica Wide", 0, 11)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        cbbmarca.setFont(new java.awt.Font("Xperia", 0, 11)); // NOI18N
        cbbmarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nexus", "Google", "Lenovo", "Huaiwei", "Sony", "Apple", "Samsung", "Alcatel", "LG", "Otra" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbbmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(cbbmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 460, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Opciones ti= new Opciones ();
                this.setVisible(false);
                ti.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPantallaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      //    Clase R=new Clase(); //CREANDO UN OBJETO R DE LA CLASE Clase


        movil R=new movil();
        float pantalla, RAM, precio,principal,secundaria,flash;  //DECLARACION DE LAS VARIABLES A USAR
int puntaje = 0, garantia, bateria, cpu,gpu;
String marca;
try{
marca = cbbmarca.getItemAt(cbbmarca.getSelectedIndex()).toString();
//mostrar+="\nmarca de su celular"+F.getItemAt(F.getSelectedIndex());
pantalla=Float.parseFloat(txtPantalla.getText());
bateria=Integer.parseInt(txtBateria.getText());
//marca = cbbmarca.getSelectedItem();
principal=Float.parseFloat(txtPrincipal.getText());
secundaria=Float.parseFloat(txtSecundaria.getText());
flash=Float.parseFloat(txtPrincipal.getText());
precio=Float.parseFloat(txtPrecio.getText());
garantia=Integer.parseInt(txtGarantia.getText());
cpu=Integer.parseInt(txtCpu.getText());
gpu=Integer.parseInt(txtGpu.getText());
RAM=Float.parseFloat(txtRam.getText());
//puntaje = int puntaje
 puntaje+=R.bateriaPantalla(pantalla, bateria);
 puntaje+=R.referenciaDeMarca(marca);
 R.setArrayPix(0,principal);
 R.setArrayPix(0,secundaria);
 R.setArrayPix(0,flash);
  puntaje+=R.pixelaje();
  puntaje+=R.precio(precio);
  puntaje+=R.garantia(garantia);
  puntaje+=R.cpu(cpu);
  puntaje+=R.cpu(gpu);
   puntaje+=R.RAM(RAM);
        
        JOptionPane.showMessageDialog(null, "EL PUNTAJE TOTAL ES:  " +puntaje+ 
                " \n Y el veredicto es:  " +R.mensaje(puntaje));
        
    }
        catch(Exception e){
  //This catch block catches all the exceptions
             JOptionPane.showMessageDialog(null, "ERROR REVISAR LOS DATOS INGRESADOS:  " );
}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIA4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIA4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIA4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIA4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIA4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbbmarca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField txtBateria;
    private javax.swing.JTextField txtCamara;
    private javax.swing.JTextField txtCpu;
    private javax.swing.JTextField txtFlash;
    private javax.swing.JTextField txtGarantia;
    private javax.swing.JTextField txtGpu;
    private javax.swing.JTextField txtPantalla;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrincipal;
    private javax.swing.JTextField txtRam;
    private javax.swing.JTextField txtSecundaria;
    // End of variables declaration//GEN-END:variables
}
