/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package guia5;

import guia5.Opciones;
import java.awt.event.KeyEvent;

/**
 *
 * @author marcello
 */
public class GUIA3 extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public GUIA3() {
        initComponents();
        this.setLocationRelativeTo(null);
    this.J.setEnabled(false);
    this.K.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        G = new javax.swing.JCheckBox();
        H = new javax.swing.JCheckBox();
        I = new javax.swing.JCheckBox();
        J = new javax.swing.JTextField();
        K = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        L = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        A = new javax.swing.JTextField();
        B = new javax.swing.JTextField();
        C = new javax.swing.JTextField();
        D = new javax.swing.JTextField();
        E = new javax.swing.JTextField();
        F = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Cpu Numero de Nucleos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 63, -1, -1));

        jLabel3.setText("Tamaño de la pantalla:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 98, -1, -1));

        jLabel4.setText("Cantidad de RAM:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 136, -1, -1));

        jLabel5.setText("Tiempo De Garantia:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 177, -1, -1));

        jLabel6.setText("Precio:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 215, -1, -1));

        jLabel7.setText("Marca:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 253, -1, -1));

        jLabel8.setText("Camaras:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 288, -1, -1));

        G.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        G.setText("Principal");
        G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GActionPerformed(evt);
            }
        });
        getContentPane().add(G, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 329, -1, -1));

        H.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        H.setText("Secundaria");
        H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HActionPerformed(evt);
            }
        });
        getContentPane().add(H, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 329, -1, -1));

        I.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        I.setText("Flash");
        getContentPane().add(I, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 329, -1, -1));

        J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JActionPerformed(evt);
            }
        });
        J.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JKeyTyped(evt);
            }
        });
        getContentPane().add(J, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 370, 98, -1));

        K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KActionPerformed(evt);
            }
        });
        K.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KKeyTyped(evt);
            }
        });
        getContentPane().add(K, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 370, 96, -1));

        jButton1.setFont(new java.awt.Font("Hall Fetica Wide", 0, 11)); // NOI18N
        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 403, -1, -1));

        L.setEditable(false);
        L.setColumns(20);
        L.setRows(5);
        jScrollPane1.setViewportView(L);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 437, 383, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 44, 450, 10));

        jToggleButton1.setFont(new java.awt.Font("Hall Fetica Wide", 0, 11)); // NOI18N
        jToggleButton1.setText("Regresar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 544, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });
        A.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AKeyTyped(evt);
            }
        });
        jPanel1.add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 58, 205, -1));

        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });
        B.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BKeyTyped(evt);
            }
        });
        jPanel1.add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 96, 206, -1));

        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });
        C.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CKeyTyped(evt);
            }
        });
        jPanel1.add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 134, 206, -1));

        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });
        D.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DKeyTyped(evt);
            }
        });
        jPanel1.add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 172, 206, -1));

        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EActionPerformed(evt);
            }
        });
        E.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EKeyTyped(evt);
            }
        });
        jPanel1.add(E, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 210, 206, -1));

        F.setFont(new java.awt.Font("Hall Fetica Wide", 0, 11)); // NOI18N
        F.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LENONO", "NEXUS", "PIXIE", "HUAWEI", "SONY", "APPLE", "SAMSUNG", "ALCATEL", "LG", "BMOVILE", "AMMGO" }));
        F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FActionPerformed(evt);
            }
        });
        jPanel1.add(F, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 248, -1, -1));

        jButton2.setFont(new java.awt.Font("Hall Fetica Wide", 0, 11)); // NOI18N
        jButton2.setText("cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 11, -1, -1));

        jLabel1.setFont(new java.awt.Font("Xperia", 1, 11)); // NOI18N
        jLabel1.setText("guia 3: VENTA DE MOVILES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 16, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public String validar()  {     
String salida="";


if (G.isSelected()) {


salida+="\nLa camara principal es: " + G.getText();


} 

if (H.isSelected()) {

salida+="\nLa camara secundaria es: " + H.getText();


} 

if (I.isSelected()) {

salida+="\nLa camara flash es: " + I.getText();


}
return salida;






}
   

    private void HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HActionPerformed
        // TODO add your handling code here:
        if (G.isSelected())
K.setEnabled(true);
else
K.setEnabled(false);
    }//GEN-LAST:event_HActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        // TODO add your handling code here:
        evt.setSource((char)KeyEvent.VK_CLEAR);
        B.requestFocus();
    }//GEN-LAST:event_AActionPerformed

    private void JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JActionPerformed

    private void KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AKeyTyped
       char k = evt.getKeyChar();
        if (!Character.isDigit(k) ) {
            evt.consume();
            getToolkit().beep();
// TODO add your handling code here:
    }
  
        if (this.A.getText().length() == 2) {
            evt.consume();
            getToolkit().beep();
        }
// TODO add your handling code here:
        
    }//GEN-LAST:event_AKeyTyped

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        // TODO add your handling code here:
        evt.setSource((char)KeyEvent.VK_CLEAR);
        C.requestFocus();
    }//GEN-LAST:event_BActionPerformed

    private void BKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BKeyTyped
  char k = evt.getKeyChar();
        if (!Character.isDigit(k) && (k != '.')) {
            evt.consume();
            getToolkit().beep();// TODO add your handling code here:
    }
        if ((k == '.') && (B.getText().contains("."))) {
            evt.consume();
            getToolkit().beep();
        }
        if (this.B.getText().length() == 3) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_BKeyTyped

    private void CKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CKeyTyped
       char k = evt.getKeyChar();
        if (!Character.isDigit(k) && (k != '.')) {
            evt.consume();
            getToolkit().beep();// TODO add your handling code here:
    }
        if ((k == '.') && (C.getText().contains("."))) {
            evt.consume();
            getToolkit().beep();
        }
        if (this.C.getText().length() == 3) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_CKeyTyped

    private void DKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DKeyTyped
        char k = evt.getKeyChar();
        if (!Character.isDigit(k) ) {
            evt.consume();
            getToolkit().beep();// TODO add your handling code here:
    }
                if (this.D.getText().length() == 12) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_DKeyTyped

    private void EKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EKeyTyped
        char k = evt.getKeyChar();
        if (!Character.isDigit(k) && (k != '.')) {
            evt.consume();
            getToolkit().beep();// TODO add your handling code here:
    }
        if ((k == '.') && (E.getText().contains("."))) {
            evt.consume();
            getToolkit().beep();
        }
        if (this.E.getText().length() == 6) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_EKeyTyped

    private void JKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JKeyTyped
char k = evt.getKeyChar();
        if (!Character.isDigit(k) && (k != '.')) {
            evt.consume();
            getToolkit().beep();// TODO add your handling code here:
    }
        if ((k == '.') && (J.getText().contains("."))) {
            evt.consume();
            getToolkit().beep();
        }
        if (this.J.getText().length() == 4) {
            evt.consume();
            getToolkit().beep();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_JKeyTyped

    private void KKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KKeyTyped
char k = evt.getKeyChar();
        if (!Character.isDigit(k) && (k != '.')) {
            evt.consume();
            getToolkit().beep();// TODO add your handling code here:
    }
        if ((k == '.') && (K.getText().contains("."))) {
            evt.consume();
            getToolkit().beep();
        }
        if (this.K.getText().length() == 4) {
            evt.consume();
            getToolkit().beep();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_KKeyTyped

    private void GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GActionPerformed
if (G.isSelected())
J.setEnabled(true);
else
J.setEnabled(false);

  
 // TODO add your handling code here:
    }//GEN-LAST:event_GActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Y= this.A.getText();
        String M= this.B.getText();
        String N= this.C.getText();
        String O= this.D.getText();
        String P= this.E.getText();
        String mostrar="";
        mostrar+="\nCPU es"+Y;
        mostrar+="\nTamaño es"+M;
        mostrar+="\nRAM es"+N;
        mostrar+="\nTiempo es"+O;
        mostrar+="\nPrecio es"+P;
        mostrar+=validar();
        mostrar+="\nmarca de su celular"+F.getItemAt(F.getSelectedIndex());
        L.setText(mostrar);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        // TODO add your handling code here:
        evt.setSource((char)KeyEvent.VK_CLEAR);
        E.requestFocus();
    }//GEN-LAST:event_DActionPerformed

    private void EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        Opciones ar = new Opciones ();
        this.setVisible(false);
        ar.setVisible (true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        // TODO add your handling code here:
        evt.setSource((char)KeyEvent.VK_CLEAR);
        D.requestFocus();
    }//GEN-LAST:event_CActionPerformed
        
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIA3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIA3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIA3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIA3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIA3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JTextField B;
    private javax.swing.JTextField C;
    private javax.swing.JTextField D;
    private javax.swing.JTextField E;
    private javax.swing.JComboBox F;
    private javax.swing.JCheckBox G;
    private javax.swing.JCheckBox H;
    private javax.swing.JCheckBox I;
    private javax.swing.JTextField J;
    private javax.swing.JTextField K;
    private javax.swing.JTextArea L;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
