/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia5;

import javax.swing.JOptionPane;

/**
 *
 * @author marcello
 */
public class VolumenEsfera extends javax.swing.JFrame {

    /**
     * Creates new form VolumenEsfera
     */
    public VolumenEsfera() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Rad = new javax.swing.JRadioButton();
        Diam = new javax.swing.JRadioButton();
        Ingrese = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Result = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, 19));

        jLabel2.setText("Calcular el volumen de una esfera, ingresar Radio o Diametro: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, -1, 22));

        jLabel3.setText("Escoja una opcion:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 99, -1, -1));

        jLabel4.setText("Ingrese dato numerico:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 149, -1, -1));

        buttonGroup1.add(Rad);
        Rad.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        Rad.setText("Radio");
        Rad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadActionPerformed(evt);
            }
        });
        getContentPane().add(Rad, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 95, -1, -1));

        buttonGroup1.add(Diam);
        Diam.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        Diam.setText("Diametro");
        getContentPane().add(Diam, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 95, -1, -1));

        Ingrese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreseActionPerformed(evt);
            }
        });
        Ingrese.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IngreseKeyTyped(evt);
            }
        });
        getContentPane().add(Ingrese, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 146, 78, -1));

        jButton1.setFont(new java.awt.Font("Hall Fetica Wide", 0, 11)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 184, -1, -1));

        Result.setColumns(20);
        Result.setRows(5);
        Result.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ResultKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(Result);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 216, 344, 137));

        jButton2.setFont(new java.awt.Font("Hall Fetica Wide", 0, 11)); // NOI18N
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 364, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Xperia", 1, 11)); // NOI18N
        jLabel1.setText("GUIA 1: Operacion 3");
        jLabel1.setMaximumSize(new java.awt.Dimension(156, 120));
        jLabel1.setMinimumSize(new java.awt.Dimension(156, 120));
        jLabel1.setPreferredSize(new java.awt.Dimension(137, 120));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 11, 170, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadActionPerformed

    private void IngreseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        OperacionesGuia1 vi= new OperacionesGuia1 ();
        this.setVisible(false);
        vi.setVisible (true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void IngreseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IngreseKeyTyped
        // TODO add your handling code here:
        char validar =evt.getKeyChar();
      if (Character.isLetter(validar)){
          evt.consume();
      }
    }//GEN-LAST:event_IngreseKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (Rad.isSelected() && !Ingrese.getText().equals("")){
            double radio, volumen;
            radio=Double.parseDouble(Ingrese.getText());
            volumen=Math.PI*Math.pow(radio, 3)*0.75;
            Result.setText("Resultado de Volumen de Esfera:"+volumen);
        }
        else if(Diam.isSelected() &&! Ingrese.getText().equals("")){ 
            double diametro, volumen, radio;
            diametro=Double.parseDouble(Ingrese.getText());
            radio=diametro/2;
            volumen=Math.pow(radio, 3)*0.75;
            Result.setText("Resultado de Volumen de Esfera:"+volumen);
        }
        else { 
            JOptionPane.showMessageDialog(null,"Proporcione medida de Radio o Diametro");
             }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ResultKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ResultKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VolumenEsfera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VolumenEsfera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VolumenEsfera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VolumenEsfera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VolumenEsfera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Diam;
    private javax.swing.JTextField Ingrese;
    private javax.swing.JRadioButton Rad;
    private javax.swing.JTextArea Result;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
